// Generated by CoffeeScript 1.6.1

/*
 MGA-1DSM part: jumping from one moon to another
 
 @author: mmarcusx@gmail.com
*/


/*
    classes
*/


(function() {
  var mga_part;

  mga_part = (function() {

    function mga_part(seq, tof, t0, v_inf) {
      var invalid_tof, t, x;
      if (seq.length < 2) {
        throw 'ValueError: sequence needs at least two bodies';
      }
      this.central_mu = 0.0;
      if (tof.length !== (seq.length - 1)) {
        throw 'ValueError: tof sequence has the wrong length';
      }
      invalid_tof = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = tof.length; _i < _len; _i++) {
          t = tof[_i];
          if (t.length !== 2) {
            _results.push(t);
          }
        }
        return _results;
      })();
      if (invalid_tof.length !== 0) {
        throw 'ValueError: tof sequence must consist of 2-tuples';
      }
      this.seq = seq;
      this.tof = tof;
      this.t0 = t0;
      this.vi_inf = v_inf;
      this.dim = 4 * (seq.length - 1);
      this.bounds = (function() {
        var _i, _ref, _results;
        _results = [];
        for (x = _i = 1, _ref = this.dim; 1 <= _ref ? _i <= _ref : _i >= _ref; x = 1 <= _ref ? ++_i : --_i) {
          _results.push([-5.12, 5.12]);
        }
        return _results;
      }).call(this);
    }

    mga_part.prototype.objfun = function(x) {
      var T, i;
      T = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= dim ? _i < dim : _i > dim; i = 0 <= dim ? ++_i : --_i) {
          if (i + 1 % 4 === 0) {
            _results.push(x[i]);
          }
        }
        return _results;
      })();
      return retval;
    };

    mga_part.prototype.feasible = function(x) {
      var elem, i, _i, _len;
      for (i = _i = 0, _len = x.length; _i < _len; i = ++_i) {
        elem = x[i];
        if (!((this.bounds[i][0] <= elem && elem <= this.bounds[i][1]))) {
          return false;
        }
      }
      return true;
    };

    return mga_part;

  })();

  /*
      main namespace
  */


  this.mga_partbox = {
    genprob: function() {
      var prob;
      console.log('generate problem');
      try {
        prob = new mga_part([europa, io], [[4, 50]], 23, 24);
      } catch (error) {
        alert(error);
      }
      return 0;
    }
  };

  this.wtf = 'bla';

}).call(this);
